class RequestView:
    req: int
    stream: int
    ready_ms: float
    service_ms: float
    waiters: int
    def __init__(
        self, req: int, stream: int, ready_ms: float, service_ms: float, waiters: int = 0
    ) -> None: ...

def version() -> str: ...
def select_fifo(ready_ms: list[float], k: int) -> list[int]: ...
def select_fifo_views(queue: list[RequestView], k: int) -> list[int]: ...
def select_sjf(queue: list[RequestView], k: int, now: float, starve_ms: float) -> list[int]: ...
