// tracon scheduler service: the same decision core (core/src/kernels.hpp),
// reachable over gRPC. RequestViews in, queue positions out — identical to the
// pybind11 seam, so parity between the two transports is a standing test.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: scheduler.proto

package schedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           int64                  `protobuf:"varint,1,opt,name=req,proto3" json:"req,omitempty"`                         // caller-side handle (queue position)
	Stream        int32                  `protobuf:"varint,2,opt,name=stream,proto3" json:"stream,omitempty"`                   // interned stream id
	ReadyMs       float64                `protobuf:"fixed64,3,opt,name=ready_ms,json=readyMs,proto3" json:"ready_ms,omitempty"` // when the request became ready
	ServiceMs     float64                `protobuf:"fixed64,4,opt,name=service_ms,json=serviceMs,proto3" json:"service_ms,omitempty"`
	Waiters       int32                  `protobuf:"varint,5,opt,name=waiters,proto3" json:"waiters,omitempty"` // chains blocked on this request's completion
	Warm          int32                  `protobuf:"varint,6,opt,name=warm,proto3" json:"warm,omitempty"`       // 1 if context resident on a free executor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestView) Reset() {
	*x = RequestView{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestView) ProtoMessage() {}

func (x *RequestView) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestView.ProtoReflect.Descriptor instead.
func (*RequestView) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *RequestView) GetReq() int64 {
	if x != nil {
		return x.Req
	}
	return 0
}

func (x *RequestView) GetStream() int32 {
	if x != nil {
		return x.Stream
	}
	return 0
}

func (x *RequestView) GetReadyMs() float64 {
	if x != nil {
		return x.ReadyMs
	}
	return 0
}

func (x *RequestView) GetServiceMs() float64 {
	if x != nil {
		return x.ServiceMs
	}
	return 0
}

func (x *RequestView) GetWaiters() int32 {
	if x != nil {
		return x.Waiters
	}
	return 0
}

func (x *RequestView) GetWarm() int32 {
	if x != nil {
		return x.Warm
	}
	return 0
}

type SelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kernel        string                 `protobuf:"bytes,1,opt,name=kernel,proto3" json:"kernel,omitempty"` // fifo | sjf | unblock | affinity | tracon
	Queue         []*RequestView         `protobuf:"bytes,2,rep,name=queue,proto3" json:"queue,omitempty"`
	K             int64                  `protobuf:"varint,3,opt,name=k,proto3" json:"k,omitempty"`
	Now           float64                `protobuf:"fixed64,4,opt,name=now,proto3" json:"now,omitempty"`
	StarveMs      float64                `protobuf:"fixed64,5,opt,name=starve_ms,json=starveMs,proto3" json:"starve_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRequest) Reset() {
	*x = SelectRequest{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequest) ProtoMessage() {}

func (x *SelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequest.ProtoReflect.Descriptor instead.
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *SelectRequest) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *SelectRequest) GetQueue() []*RequestView {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *SelectRequest) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SelectRequest) GetNow() float64 {
	if x != nil {
		return x.Now
	}
	return 0
}

func (x *SelectRequest) GetStarveMs() float64 {
	if x != nil {
		return x.StarveMs
	}
	return 0
}

type SelectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []int64                `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"` // selected queue positions, dispatch order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectResponse) Reset() {
	*x = SelectResponse{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectResponse) ProtoMessage() {}

func (x *SelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectResponse.ProtoReflect.Descriptor instead.
func (*SelectResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *SelectResponse) GetIndices() []int64 {
	if x != nil {
		return x.Indices
	}
	return nil
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\x06tracon\"\x9f\x01\n" +
	"\vRequestView\x12\x10\n" +
	"\x03req\x18\x01 \x01(\x03R\x03req\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\x05R\x06stream\x12\x19\n" +
	"\bready_ms\x18\x03 \x01(\x01R\areadyMs\x12\x1d\n" +
	"\n" +
	"service_ms\x18\x04 \x01(\x01R\tserviceMs\x12\x18\n" +
	"\awaiters\x18\x05 \x01(\x05R\awaiters\x12\x12\n" +
	"\x04warm\x18\x06 \x01(\x05R\x04warm\"\x8f\x01\n" +
	"\rSelectRequest\x12\x16\n" +
	"\x06kernel\x18\x01 \x01(\tR\x06kernel\x12)\n" +
	"\x05queue\x18\x02 \x03(\v2\x13.tracon.RequestViewR\x05queue\x12\f\n" +
	"\x01k\x18\x03 \x01(\x03R\x01k\x12\x10\n" +
	"\x03now\x18\x04 \x01(\x01R\x03now\x12\x1b\n" +
	"\tstarve_ms\x18\x05 \x01(\x01R\bstarveMs\"*\n" +
	"\x0eSelectResponse\x12\x18\n" +
	"\aindices\x18\x01 \x03(\x03R\aindices2D\n" +
	"\tScheduler\x127\n" +
	"\x06Select\x12\x15.tracon.SelectRequest\x1a\x16.tracon.SelectResponseB\x1bZ\x19traconsvc/schedpb;schedpbb\x06proto3"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_scheduler_proto_goTypes = []any{
	(*RequestView)(nil),    // 0: tracon.RequestView
	(*SelectRequest)(nil),  // 1: tracon.SelectRequest
	(*SelectResponse)(nil), // 2: tracon.SelectResponse
}
var file_scheduler_proto_depIdxs = []int32{
	0, // 0: tracon.SelectRequest.queue:type_name -> tracon.RequestView
	1, // 1: tracon.Scheduler.Select:input_type -> tracon.SelectRequest
	2, // 2: tracon.Scheduler.Select:output_type -> tracon.SelectResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
