# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\x06tracon\"o\n\x0bRequestView\x12\x0b\n\x03req\x18\x01 \x01(\x03\x12\x0e\n\x06stream\x18\x02 \x01(\x05\x12\x10\n\x08ready_ms\x18\x03 \x01(\x01\x12\x12\n\nservice_ms\x18\x04 \x01(\x01\x12\x0f\n\x07waiters\x18\x05 \x01(\x05\x12\x0c\n\x04warm\x18\x06 \x01(\x05\"n\n\rSelectRequest\x12\x0e\n\x06kernel\x18\x01 \x01(\t\x12\"\n\x05queue\x18\x02 \x03(\x0b\x32\x13.tracon.RequestView\x12\t\n\x01k\x18\x03 \x01(\x03\x12\x0b\n\x03now\x18\x04 \x01(\x01\x12\x11\n\tstarve_ms\x18\x05 \x01(\x01\"!\n\x0eSelectResponse\x12\x0f\n\x07indices\x18\x01 \x03(\x03\x32\x44\n\tScheduler\x12\x37\n\x06Select\x12\x15.tracon.SelectRequest\x1a\x16.tracon.SelectResponseB\x1bZ\x19traconsvc/schedpb;schedpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031traconsvc/schedpb;schedpb'
  _globals['_REQUESTVIEW']._serialized_start=27
  _globals['_REQUESTVIEW']._serialized_end=138
  _globals['_SELECTREQUEST']._serialized_start=140
  _globals['_SELECTREQUEST']._serialized_end=250
  _globals['_SELECTRESPONSE']._serialized_start=252
  _globals['_SELECTRESPONSE']._serialized_end=285
  _globals['_SCHEDULER']._serialized_start=287
  _globals['_SCHEDULER']._serialized_end=355
# @@protoc_insertion_point(module_scope)
